### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by diaodeyi** [jackyjsy/SGGAN#3]
Thanks for your beatutiful work , I want to konw why the input of the discriminator is only the image , the classfication information as the conditional information to the generator ,should also  be  the input of  discriminator.

**Comment by jackyjsy** [comment]
There's an auxiliary classifier embedded in the discriminator, which means that the discriminator has a discrimination output and a classification output as two heads. So there's no conditional info input to the discriminator. (details can be found in paper ACGAN)

ACGAN: https://arxiv.org/abs/1610.09585

**Comment by diaodeyi** [comment]
thank you

**Comment by diaodeyi** [comment]
Sorry to bother again, as i kown , the ACGAN try to solve the multi-class problem, but the SGGAN need to solve the multi-label problem right? So how can this structure can differentiate different labels of single image without other loss or trick ,but just use a  classfication loss in the ACGAN.
