### ISSUE TITLE
About  segmentor 

### ISSUE THREAD

**Issue by diaodeyi** [jackyjsy/SGGAN#4]
Thanks for your beautiful work，I want to know that since you can get the segmentation with the landmark , why you design a segmentor in addition？

**Comment by jackyjsy** [comment]
The segmentor aims to guide the generator to translate input images into target spatial configurations, by providing gradient information during back propagation using the segmentation loss. Details can be found in our paper SGGAN https://arxiv.org/abs/1901.01569
